### ISSUE TITLE
Description doesn't suggest fastq support

### ISSUE THREAD

**Issue by tseemann** [nhoffman/fastalite#3]
![image](https://user-images.githubusercontent.com/453972/66165662-96ae9a80-e678-11e9-885f-0e5351794043.png)

Or is it too slow for fastq in real world?

**Comment by nhoffman** [comment]
Thanks. Good point. The criteria for "too slow" depends on the application, but it's totally fine for miseq-scale sequencing data in my experience.

**Comment by tseemann** [comment]
User-dependent tolerance / patience :-)
